# test_fabric_health.py
import os
import unittest
import pathlib
import csv
import tracemalloc
import time

class TestUnivacFabricHealth(unittest.TestCase):
    """
    Automated health validation suite targeting path bindings,
    log file access states, and memory footprint leakage behaviors.
    """

    @classmethod
    def setUpClass(cls):
        """Initializes testing parameters and system boundary profiles."""
        cls.workspace_dir = pathlib.Path(__file__).parent.resolve()
        cls.log_dir = cls.workspace_dir / "logs"
        cls.target_csv = cls.workspace_dir / "visio_mapping.csv"
        cls.target_html = cls.workspace_dir / "execution_report.html"
        cls.target_template = cls.workspace_dir / "report_template.html"

    def test_01_file_path_and_template_structures(self):
        """Verifies presence and read access patterns for critical layout templates."""
        print("\n[TEST-01] Validating core workspace template dependencies...")
        
        # Ensure our base tracking structures are present or have templates ready
        self.assertTrue(self.target_template.exists(), f"Missing template path reference: {self.target_template}")
        
        if self.target_csv.exists():
            self.assertTrue(os.access(self.target_csv, os.R_OK), "CSV exists but lacks file system read access permissions.")

    def test_02_log_directory_allocation(self):
        """Confirms that background log file targets are allocated and writable."""
        print("\n[TEST-02] Verifying log footprint storage targets...")
        
        if self.log_dir.exists():
            self.assertTrue(self.log_dir.is_dir(), "The allocated logs path is occupied by a non-directory element.")
            # Verify system visibility for our script log hooks
            expected_logs = ["monitor_hazards.log", "report_sync.log", "telemetry_stream.log"]
            for log_name in expected_logs:
                log_path = self.log_dir / log_name
                if log_path.exists():
                    print(f"     ↳ Discovered active logging channel: {log_name}")

    def test_03_csv_schema_compliance(self):
        """Parses active CSV records to ensure structural row headers conform to the Visio layout rules."""
        print("\n[TEST-03] Checking Visio Data Visualizer row schema rules...")
        
        if not self.target_csv.exists():
            self.skipTest("Telemetry file 'visio_mapping.csv' not yet generated by live streams. Skipping check.")

        expected_headers = ["Process ID", "Node Name", "Hardware Mapping", "Resource Load (%)", "Status Indicator", "Shape Type", "Next Node Link"]
        
        with open(self.target_csv, mode='r', newline='', encoding='utf-8') as f:
            reader = csv.reader(f)
            headers = next(reader, None)
            
            self.assertIsNotNone(headers, "The telemetry data map file appears to be completely empty.")
            # Verify required template columns align properly
            for header in expected_headers:
                self.assertIn(header, headers, f"Critical layout compliance header field missing: '{header}'")

    def test_04_memory_leakage_runtime_bound(self):
        """
        Launches memory profiler hooks over mock iteration blocks.
        Verifies that rapid telemetry adjustments do not leak data structures on the heap.
        """
        print("\n[TEST-04] Executing runtime heap snapshot tracking to catch memory leaks...")
        
        # Initialize the Python memory allocator tracker
        tracemalloc.start()
        
        # Capture baseline snapshot memory frame
        snapshot_start = tracemalloc.take_snapshot()
        
        # Simulate an extended testing burst loop modifying memory structures
        mock_leaking_buffer = []
        for cycle in range(500):
            # Emulate incoming node metrics
            sample_frame = {
                "id": f"N-{cycle:03d}",
                "metric": float(cycle) * 1.5,
                "status": "Nominal" if cycle % 10 != 0 else "Critical"
            }
            mock_leaking_buffer.append(sample_frame)
            
            # Clear or process elements to preserve standard memory footprint stability boundaries
            if len(mock_leaking_buffer) > 10:
                mock_leaking_buffer.pop(0)

        # Clear final validation array remnants
        mock_leaking_buffer.clear()
        
        # Capture post-execution snapshot memory frame
        snapshot_end = tracemalloc.take_snapshot()
        tracemalloc.stop()
        
        # Evaluate memory difference footprints
        top_stats = snapshot_end.compare_to(snapshot_start, 'lineno')
        
        total_allocated_diff_bytes = sum(stat.size_diff for stat in top_stats)
        print(f"     ↳ Allocation variance over test iteration: {total_allocated_diff_bytes} bytes.")
        
        # Set a reasonable health safety boundary of 50 KB maximum heap drift for small transient state tests
        MAX_ALLOWED_DRIFT_BYTES = 51200  
        self.assertLess(total_allocated_diff_bytes, MAX_ALLOWED_DRIFT_BYTES, 
                        f"Excessive memory allocation drift identified: {total_allocated_diff_bytes} bytes leaked on the heap!")

if __name__ == "__main__":
    print("=========================================================")
    print("🧪 UNIVAC-IX: Running Infrastructure Health & Integrity Tests")
    print("=========================================================")
    unittest.main()
