# test_fabric_health.py
import os
import unittest
import pathlib
import csv
import tracemalloc
import re

class TestUnivacFabricHealth(unittest.TestCase):
    """
    Automated health validation suite targeting path bindings,
    log file access states, and complete HTML template token resolution.
    """

    @classmethod
    def setUpClass(cls):
        """Initializes testing parameters and system boundary profiles."""
        cls.workspace_dir = pathlib.Path(__file__).parent.resolve()
        cls.log_dir = cls.workspace_dir / "logs"
        cls.target_csv = cls.workspace_dir / "visio_mapping.csv"
        cls.target_html = cls.workspace_dir / "execution_report.html"
        cls.target_template = cls.workspace_dir / "report_template.html"

    def test_01_file_path_and_template_structures(self):
        """Verifies presence and read access patterns for critical layout templates."""
        print("\n[TEST-01] Validating core workspace template dependencies...")
        self.assertTrue(self.target_template.exists(), f"Missing template path reference: {self.target_template}")
        
        if self.target_csv.exists():
            self.assertTrue(os.access(self.target_csv, os.R_OK), "CSV exists but lacks file system read access permissions.")

    def test_02_log_directory_allocation(self):
        """Confirms that background log file targets are allocated and writable."""
        print("\n[TEST-02] Verifying log footprint storage targets...")
        if self.log_dir.exists():
            self.assertTrue(self.log_dir.is_dir(), "The allocated logs path is occupied by a non-directory element.")
            expected_logs = ["monitor_hazards.log", "report_sync.log", "telemetry_stream.log"]
            for log_name in expected_logs:
                log_path = self.log_dir / log_name
                if log_path.exists():
                    print(f"     ↳ Discovered active logging channel: {log_name}")

    def test_03_csv_schema_compliance(self):
        """Parses active CSV records to ensure structural row headers conform to the Visio layout rules."""
        print("\n[TEST-03] Checking Visio Data Visualizer row schema rules...")
        if not self.target_csv.exists():
            self.skipTest("Telemetry file 'visio_mapping.csv' not yet generated by live streams. Skipping check.")

        expected_headers = ["Process ID", "Node Name", "Hardware Mapping", "Resource Load (%)", "Status Indicator", "Shape Type", "Next Node Link"]
        with open(self.target_csv, mode='r', newline='', encoding='utf-8') as f:
            reader = csv.reader(f)
            headers = next(reader, None)
            
            self.assertIsNotNone(headers, "The telemetry data map file appears to be completely empty.")
            for header in expected_headers:
                self.assertIn(header, headers, f"Critical layout compliance header field missing: '{header}'")

    def test_04_html_template_token_resolution(self):
        """
        Scans the generated report file using regex patterns to verify that all 9 unique
        node peaks and both flush counter template variables are fully compiled.
        """
        print("\n[TEST-04] Executing regex compliance scan for HTML token compilation...")
        if not self.target_html.exists():
            self.skipTest("Output file 'execution_report.html' not yet compiled. Skipping token leak validation.")

        with open(self.target_html, "r", encoding="utf-8") as f_html:
            html_content = f_html.read()

        # Define the exact list of all required system template handles that must be cleared
required_compiled_tokens = [
    "STELLAR_FLUSHES", "BIOMASS_FLUSHES",
    "TIGER_PEAK", "BENNAN_PEAK", "STELLAR_PEAK",
    "TURNKEY_PEAK", "TURF_PEAK", "BIOMASS_PEAK",
    "WATCHERS_PEAK", "CAT_SUB_PEAK", "FUEL_PEAK",
    "SIEMENS_PEAK", "KIRKLAND_PEAK", "STEAMPUNK_PEAK",
    "STELLAR_NET_PEAK", "STELLAR_LIFE_PEAK", "STELLAR_GREEN_PEAK",
    "STELLAR_GRID_PEAK", "STELLAR_RANGE_PEAK", "QUALCOMM_DOC_PEAK",
    # NEW COMPLIANCE TOKENS
    "LOCK_PEAK", "HVAC_PEAK", "AVIATION_PEAK", "ASTRONOMY_PEAK"
]
        # Scan for raw uncompiled curly-brace patterns (e.g., {{TIGER_PEAK}})
        for token in required_compiled_tokens:
            pattern = f"\\{{\\{{\\s*{token}\\s*\\}}\\}}"
            token_leak_match = re.search(pattern, html_content)
            
            # Assert that the pattern returns No Match, confirming complete resolution
            self.assertIsNone(
                token_leak_match, 
                f"❌ COMPILATION FAULT LEAK: Template token '{{{{{token}}}}}' was left unparsed in the production HTML output!"
            )
        
        print("     ↳ Success: All 9 unique hardware node tokens and 2 override metrics verified clear.")

    def test_05_memory_leakage_runtime_bound(self):
        """Launches memory profiler hooks over mock blocks to check for heap stability."""
        print("\n[TEST-05] Executing runtime heap snapshot tracking to catch memory leaks...")
        tracemalloc.start()
        snapshot_start = tracemalloc.take_snapshot()
        
        mock_buffer = []
        for cycle in range(500):
            sample_frame = {
                "id": f"N-{cycle:03d}",
                "metric": float(cycle) * 1.5,
                "status": "Nominal" if cycle % 10 != 0 else "Critical"
            }
            mock_buffer.append(sample_frame)
            if len(mock_buffer) > 10:
                mock_buffer.pop(0)

        mock_buffer.clear()
        snapshot_end = tracemalloc.take_snapshot()
        tracemalloc.stop()
        
        top_stats = snapshot_end.compare_to(snapshot_start, 'lineno')
        total_allocated_diff_bytes = sum(stat.size_diff for stat in top_stats)
        print(f"     ↳ Allocation variance over test iteration: {total_allocated_diff_bytes} bytes.")
        
        MAX_ALLOWED_DRIFT_BYTES = 51200  # 50 KB
        self.assertLess(total_allocated_diff_bytes, MAX_ALLOWED_DRIFT_BYTES, 
                        f"Excessive memory allocation drift identified: {total_allocated_diff_bytes} bytes leaked on the heap!")

if __name__ == "__main__":
    print("=========================================================")
    print("🧪 UNIVAC-IX: Running Segmented Infrastructure Integrity Tests")
    print("=========================================================")
    unittest.main()
